ФЗ№9.версия1
SarychV/java-filmorate pull request #4
Opened 2023-07-21 10:46 UTC by SarychV

2023-07-22 12:29 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-07-22 12:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Integer, Film> films = new HashMap<>();
сюда добавьте модификатор доступа

2023-07-22 12:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == 0) film.setId(++lastGeneratedId);
вместо этой проверки, можно в 17й строке сделать:
privata int lastGenerated = 0 -- не нужно делать статиком и сразу инициализируете

2023-07-22 12:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } else {
тут лучше 1 if использовать:
```
if (!users.containsKey(user.getId())) {
   log.debug("updateUser(): " + user + " не обновлен (id =" + user.getId() + " отсутствует)");
   throw new ValidationException("id пользователя отсутствует в списке");
}
```

2023-07-22 12:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (films.containsKey(film.getId())) {
тут лучше 1 if использовать:

```
if (!films.containsKey(film.getId())) {
   log.debug("updateFilm(): " + film + " не обновлен (отсутствует)");
   throw new ValidationException();
}
```

2023-07-22 12:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        if (releaseDate.isBefore(LocalDate.of(1895, 12, 28)))
здесь можно оставить только эту проверку, так как остальные вы уже реализовали через аннотации

2023-07-22 12:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public void validate() throws ValidationException {
этот метод по идее не нужен, так как все валидационные проверки вы реализовали через аннотации

2023-07-22 12:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Integer, Film> films = new HashMap<>();
также в UserController

2023-07-22 12:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == 0) film.setId(++lastGeneratedId);
также в UserController

2023-07-23 11:26 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public void validate() throws ValidationException {
Через аннотации, согласно техническому заданию, реализовано необязательное дополнтельное задание. Основное задание предусматривает валидацию через метод. Все junit тесты написаны для метода. Наставник сказал, что валидация через аннотации проверяется postman'oм, значит если убрать метод validate(), необходимо изменить(убрать) junit тесты. Данный метод оставлен для того, чтобы показать, что основное задание выполнено.

2023-07-23 11:27 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        if (releaseDate.isBefore(LocalDate.of(1895, 12, 28)))
Через аннотации, согласно техническому заданию, реализовано необязательное дополнтельное задание. Основное задание предусматривает валидацию через метод. Все junit тесты написаны для метода. Наставник сказал, что валидация через аннотации проверяется postman'oм, значит если убрать метод validate(), необходимо изменить(убрать) junit тесты. Данный метод оставлен для того, чтобы показать, что основное задание выполнено.

2023-07-23 11:28 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } else {
Внес изменения.

2023-07-23 11:28 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (films.containsKey(film.getId())) {
Внес изменения.

2023-07-23 11:28 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == 0) film.setId(++lastGeneratedId);
Внес изменения.

2023-07-23 11:29 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Integer, Film> films = new HashMap<>();
Внес изменения.

2023-07-23 14:43 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-08-02 06:49 UTC, merged