TZ10
SarychV/java-filmorate pull request #5
Opened 2023-08-05 15:55 UTC by SarychV

2023-08-07 04:00 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-08-07 04:00 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public Map<String, String> handleMethod(final ValidationException e) {
тут надо кидать не ValiodationException, а NotFoundException (можно сделать свой кастомный класс)
его вы кидаете в случаях когда нужная сущность не найдена в storage. То есть когда все валидации прошли

2023-08-08 13:19 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int id;
Исправлено.

2023-08-08 13:31 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.selectAllFilms();
Переименовал в find..(поскольку get используется геттерами).

2023-08-08 13:32 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> selectMorePopularFilms(int size) {
Исправил.

2023-08-08 13:52 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (id <= 0) throw new ValidationException("Неверное значение идентификатора пользователя.");
Исправил.

2023-08-08 14:36 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    }
Исправил.

2023-08-08 14:36 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getId() <= 0) {
Исправил.

2023-08-08 14:36 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public Map<String, String> handleMethod(final ValidationException e) {
Исправил.

2023-08-09 06:21 UTC, ErkinKasymaliev requested changes
привет, оставил еще комменты

2023-08-09 06:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer id = 0;
инициализировать не надо, так как ссылочный тип. Если б был примитив, то надо было инициализировать

2023-08-09 06:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Integer id = 0;
инициализировать не надо

2023-08-09 06:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/NotFoundException.java
> +public class NotFoundException extends RuntimeException{
уберите в отдельный пакет в exception

2023-08-09 06:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (filmId == 0) {
тут не совсем верно. Как я ранее писал при добавлении нового фильма, у него еще нет id. Это проверка не нужна, будет так:
```
@Override
 public void add(Film film) {
    film.setId(++lastGeneratedFilmId);
    films.put(film.getId(), film)
}
```
аналогично для userStorage

2023-08-09 06:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
>          if (films.containsKey(filmId)) {
это проверка не нужна, так как id всегда будет новый, тут можно поставить проверку на filmName, если мы пытаемся добавить фильм с таким же названием, но по ТЗ это не требуется, поэтому сделайте как я написал выше

2023-08-09 06:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @PositiveOrZero
тут уберите аннотацию

2023-08-09 06:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @PositiveOrZero
тут уберите аннотацию

2023-08-09 06:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        int filmId = film.getId();
33-35 строки не нужны, валидацию на id при добавлении фильма проверять не надо, надо при обновлении или удалении

2023-08-09 11:58 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/model/NotFoundException.java
> +public class NotFoundException extends RuntimeException{
Исправил.

2023-08-09 12:05 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
>          if (films.containsKey(filmId)) {
Исправил.

2023-08-09 12:07 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @PositiveOrZero
Исправил.

2023-08-09 12:07 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @PositiveOrZero
Исправил.

2023-08-09 12:23 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer id = 0;
Исправил.

2023-08-09 12:23 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Integer id = 0;
Исправил.

2023-08-09 12:23 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        int filmId = film.getId();
Исправил.

2023-08-10 05:43 UTC, ErkinKasymaliev approved these changes
привет, теперь все круто!
Работа принята

2023-08-18 14:24 UTC, merged