Описание схемы базы данных приложения
SarychV/java-filmorate pull request #6
Opened 2023-08-21 13:38 UTC by SarychV

В файле README.md приведены ER диаграмма и ее описание для базы данных приложения, описание полей таблиц, несколько SQL запросов для получения информации о фильмах и пользователях сервиса.

2023-08-22 11:19 UTC, IHukumka commented
хорошо отрисована схема, взаимосвязи понятны и не запутаны.
описание принципов работы информативно, но не хватает полной структуры взаимодействия Приложения с БД, т.е. процесса десериализации объекта из БД.

2023-08-22 11:21 UTC, IHukumka commented
реализация друзей через две таблицы кажется громоздкой (на мой взгляд), для получения статуса заявки необходимо проверить две таблицы (во избежание потери данных).

2023-09-04 08:27 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
Правда есть моменты где надо улучшить и оптимизировать код

2023-09-04 08:27 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public void add(Film film) {
Этот метод лучше сделайте private Film add(), чтобы возвращал объект с id.

2023-09-04 08:27 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          filmService.addFilm(film);
метод filmService.addFilm(film) сделайте не void, а чтобы возвращал объект с генерированным id. И вам не нужен будет лишний вызов в БД на 35 строке. Должно быть примерно так:
```
public Film addFilm(@Valid @RequestBody Film film) {
        log.info("В фильмотеку добавляется фильм: " + film);
        Film savedFilm  = filmService.addFilm(film);
        log.info("Добавлен фильм: " + savedFilm);
        return savedFilm;
}
```
аналогично для addUser в UserController

2023-09-04 08:27 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Film modifiedFilm = filmService.findFilmById(film.getId());
здесь тоже лишний вызов, попробуйте так:
```
...{
   log.info("Вносятся изменения в фильм:" + film);
   Film modifiedFilm = filmService.updateFilm(film);
   log.info("Фильм изменен: " + modifiedFilm);
   return modifiedFilm;
}
```
аналогично для updateUser в UserController

2023-09-04 08:27 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          hasValidFilmId(film.getId());
такие проверки лучше убрать в сервис

2023-09-04 08:27 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public void update(Film film) {
лучше этот метод лучше сделайте private Film update(), чтобы возвращал объект с id.

2023-09-04 08:27 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        for (int id : ids) {
Представьте что у вас 100 000 фильмов в бд, и здесь у вас будет еще 100 000 запросов по id. Это нехорошая практика, вместо этого в sqlQuery добавьте join чтобы в одном запросе подтянуть рейтинги и жанры

2023-09-04 08:27 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        List<Integer> ids = jdbcTemplate.query(sqlQuery, (rs, num) -> rs.getInt("id"));
аналогичный коммент как и в FilmDbStorage. добавьте join-ы в запрос

2023-09-04 13:11 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public void add(Film film) {
Эркин, привет! 
Да, то, что ты предлагаешь было бы лучше, если бы я сразу реализовал возврат объетов классов User и Film в методах add() и update()  в интерфейсах FilmStorage() и UserStorage(). Необходимость возврата этих объектов я понял уже в конце выполнения задания. Когда вместо возврата поступивших в контроллеры объектов (как это предлагается в теории курса) я решил возвращать объекты из базы (мне так видится более правильным). Однако, реализация того, что ты предлагаешь в этом и последующих замечаниях потребует внесения изменений во все тесты, в классы с работой с базой данных и в классы по работе с хранилищем в памяти. Это достаточно большой объем работы. С учетом жесткого дедлайна, я не решился на внесение этих изменений, поскольку работа практически была оттестирована. Я предлагаю для данной реализации оставить ситуацию такой, какой она есть. Если ты считаешь вопрос принципиальным, то я предлагаю эти изменения сделать в следующеий итерации, сейчас у меня нет времени (с учетом того, что мне поставили срок сдать работу до конца завтрашнего дня), мне могут предложить вязть перенос обучения, если я не успею закрыть эту работу. К тому же, мне видится  этот вопрос не принципиальным, хотя еще раз повторю, что в целом я с тобой согласен.

2023-09-04 13:11 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          filmService.addFilm(film);
см. первый комментарий.

2023-09-04 13:11 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Film modifiedFilm = filmService.findFilmById(film.getId());
см. первый комментарий.

2023-09-04 13:14 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public void update(Film film) {
см. первый комментарий.

2023-09-04 13:15 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public void add(Film film) {
привет, да без проблем, этот момент оставляй как есть

2023-09-04 18:51 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        for (int id : ids) {
Еще нужно подтянуть лайки. Посмотри, пожалуйста, я реализовал то что требуется, или нет?

2023-09-04 18:51 UTC, SarychV commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          hasValidFilmId(film.getId());
Исполнил.

2023-09-05 05:07 UTC, ErkinKasymaliev approved these changes
привет, работа принята!
Оставил дополнительные комменты. Если будешь успевать, то поправь их перед мержем. Если же нет - то к следующей домашку

2023-09-05 05:07 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        "SELECT id, name, description, release_date, duration, rating_id, rating_name, genre_id, genre_name, user_id " +
хим, думаю можно так:
```
select f.*, r.name, g.name from films f
join rating r on r.film_id=f.id
join film_genre fm on fm.film_id = f.id
join genre g on g.id=fg.genre_id
```
и закоменченный код удали

2023-09-05 05:07 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        "SELECT id, name, description, release_date, duration, rating_id, rating_name, genre_id, genre_name, user_id " +
вместо f.* можешь нужные поля вставить, а не все подтягивать. И думаю, что лайки тут не нужны

2023-09-05 05:07 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmDbStorage storage) {
вот тут проглядел. Здесь используй @Qualifier.
вот так:
public FilmService(@Qualifier(name="filmDbStorage") FilmStorate storage) - надо инжектить абстракцию, то есть интерфейс. Прочитай про SOLID, как будет время

2023-09-05 05:07 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserDbStorage storage) {
здесь также
вот так:
public UserService(@Qualifier(name="userDbStorage") UserStorage storage)

2023-09-05 05:07 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaGenreService.java
> +public class MpaGenreService {
не надо так делать: раздели на отдельные сервисы MpaService, GenreService. также со storage-ми

2024-01-22 15:15 UTC, merged